using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using POST.UserInterface;

namespace POST
{
    public partial class MainForm : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public MainForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
        }

        private void MainForm_Load(object sender, EventArgs e)
        {

        }
        private void btn_user_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            UserForm userchild = new UserForm();
            userchild.MdiParent = this;
            userchild.Show();
        }
    }
}
