using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

using POST.Class;

namespace POST.UserInterface
{
    public partial class UserForm : Form
    {
        public UserForm()
        {
            InitializeComponent();
            txt_userName.Text = "Demo";
            txt_password.Text = "Abc";
            txt_salary.Text = "1000";
            txt_description.Text = "DemoTest";
            ComboGender.SelectedIndex = 1;
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource asynchronously
        }

        private void btn_save_Click(object sender, EventArgs e)
        {
            string username = txt_userName.Text.Trim();
            string gender = ComboGender.SelectedItem.ToString();
            DateTime dateOfbirth = dtDob.Value;
            string password = txt_password.Text.Trim();
            string description = txt_description.Text.Trim();
            float salary = float.Parse(txt_salary.Text.Trim());
            string phone = txt_phone.Text.Trim();
            int possitionId = 1;
            byte[] img = Public_function.converterDemo(use_Picturebox.Image);
            int active = 0;
            if (is_active.Checked)
                active = 1;
            else
                active = 0;
            ClsUser.userInsesrt(username, gender, dateOfbirth, password, description, salary, phone, active, possitionId, img);
        }
        private void use_Picturebox_Click(object sender, EventArgs e)
        {
            OpenFileDialog f = new OpenFileDialog();
            f.Filter = "Image Files(*.jpg; *.jpeg; *.gif; *.bmp)|*.jpg; *.jpeg; *.gif; *.bmp";
            if (f.ShowDialog()==DialogResult.OK)
            {
                use_Picturebox.Image = new Bitmap(f.FileName);
            }
        }

        private void btn_cancel_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void UserForm_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'pOSSQ9_DBDataSet.TBL_USER' table. You can move, or remove it, as needed.
            this.tBL_USERTableAdapter.Fill(this.pOSSQ9_DBDataSet.TBL_USER);

        }

        private void gridView1_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            MessageBox.Show("Here is Cell Click: "); 
        }
    }
}
